#%RAML 1.0 NamedExample

-
  cedula: 1230512312
  nombre: Sebastian Mejia Rodriguez
  telefono: 3005259049
  cargo: Empleado
-
  cedula: 1027662858
  nombre: Lucas Arboleda Bedoya
  telefono: 3005259049
  cargo: Gerente  